// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWau9OB4KutXDpB1ofpbdDbWAPpP1ZKSk',
    appId: '1:916804972804:web:db13222d7624249096a051',
    messagingSenderId: '916804972804',
    projectId: 'eos-chat-110a8',
    authDomain: 'eos-chat-110a8.firebaseapp.com',
    storageBucket: 'eos-chat-110a8.appspot.com',
    measurementId: 'G-3MXDFVT2F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2RDc218y9WXECsOK4EOOKz4MfTGnQiY',
    appId: '1:916804972804:android:6096edab4885ac0696a051',
    messagingSenderId: '916804972804',
    projectId: 'eos-chat-110a8',
    storageBucket: 'eos-chat-110a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqikGXuxnOVzwLuKli27sse-dKI66nYs',
    appId: '1:916804972804:ios:809d8894b876560696a051',
    messagingSenderId: '916804972804',
    projectId: 'eos-chat-110a8',
    storageBucket: 'eos-chat-110a8.appspot.com',
    iosClientId: '916804972804-atlr7l3oi8ms2lgc42l897a49fia7t5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBqikGXuxnOVzwLuKli27sse-dKI66nYs',
    appId: '1:916804972804:ios:412badeea195b15196a051',
    messagingSenderId: '916804972804',
    projectId: 'eos-chat-110a8',
    storageBucket: 'eos-chat-110a8.appspot.com',
    iosClientId: '916804972804-68ekrpbpn6feu7v0tl45mfm1j84n4b30.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChat',
  );
}
